### ISSUE TITLE
Git Not working?

### ISSUE THREAD

**Issue by JARHEAD1246** [Laumania/FireworksMania.ModTools#25]
I installed DoTween, and Git, but when i try to paste the unitask url, it says no git executables were found. i restarted unity multiple times and even reinstalled git. Help!

**Comment by Keltusar** [comment]
> I installed DoTween, and Git, but when i try to paste the unitask url, it says no git executables were found. i restarted unity multiple times and even reinstalled git. Help!

Make sure you restart your PC after you installed Git after that add unitask url

**Comment by Laumania** [comment]
> I installed DoTween, and Git, but when i try to paste the unitask url, it says no git executables were found. i restarted unity multiple times and even reinstalled git. Help!

Did you get it to work after restart as @Keltusar suggested?
