### ISSUE TITLE
Automatically installing other dependencies

### ISSUE THREAD

**Issue by daanbreur** [Laumania/FireworksMania.ModTools#8]
Using the following code it should be possible

```json
{
    "name": "com.test.depender",
    "displayName": "Test Depender",
    "version": "0.0.1",
    "unity": "2018.3",
    "description": "bla bla bla",
    "category": "Unity",
    "dependencies": {
        "com.test.dependency": "https://github.com/GitUserName/Test.Dependency.git"
    }
}
```

[Source](https://forum.unity.com/threads/custom-package-with-git-dependencies.628390/)

**Comment by Laumania** [comment]
Thanks, but I'm pretty sure I researched and tried this, but it didn't work. Else it would be perfect to include UniTask like this, as it's one less thing for modders to remember - but I'll take a look and give it a second look.

**Comment by Laumania** [comment]
Doesn't seem to work sadly:
https://issuetracker.unity3d.com/issues/package-manager-doesnt-resolve-package-dependencies-when-using-git-url-to-add-a-package-which-contains-a-git-url-dependency

At least not yet :(

> Dependencies declared with Git URLs are only supported in project manifests (<project>/Packages/manifest.json), not package manifests (package.json).

**Comment by Laumania** [comment]
Sadly doesn't work...please let me know if anybody ends up here and know how this can work :)
